version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install "sagemaker<3.0.0" boto3
  build:
    commands:
      - echo "Triggering SageMaker AI Pipeline..."
      - python aws_sagemaker/pipeline.py --role-arn $SAGEMAKER_ROLE_ARN --bucket $DATA_BUCKET --execute
